---
- name: Pull Spring image of Review App
  hosts: all
  tasks:
    - name: Pull app image
      docker_image:
        name: rajatkumariiitb/startup_review-db
        source: pull
    - name: Running the container
      docker_container:
        name: startupreview-db
        image: rajatkumariiitb/startup_review-db:latest
        state: started
        restart: yes
        ports:
          - "3306:3306"
        networks:
          - name: app-default
        volumes:
          - /storage/docker/mysql-data:/var/lib/mysql
        restart_policy: always 

